argo_cd:
  application: 'propeller'
  base_url: 'http://localhost:8080'
  danger_accept_insecure: true
postgres:
  host: 'localhost'
  port: 32833
  database: 'demo'
vault:
  base_url: 'http://localhost:32834'
  path: 'rotate/secrets'
