@startuml

skinparam component {
    BackgroundColor<<propeller>> #F2A007
}

package "CI/CD Platform" {
    component "<color:#white>CLI</color>" as prop1 << propeller >>
}

package Kubernetes {
    component Application as app
    component ArgoCD
    component "Vault Sync (Job)" as vsync

    component "<color:#white>Image</color>" as prop2 << propeller >>

    ArgoCD ..> app: Manages
    ArgoCD ..> vsync: Manages (//PreSync// hook)
}

database PostgreSQL as db #A65526
component Vault

app --> db: Store data
vsync <-- Vault: Synchronize secrets

@enduml
