apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: propeller

commonLabels:
  app.kubernetes.io/name: propeller-demo
  app.kubernetes.io/instance: integration-tests
  app.kubernetes.io/version: stable
  app.kubernetes.io/component: example-app
  app.kubernetes.io/part-of: propeller
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/created-by: postfinance
  environment: ci
  purpose: integration-testing

resources:
  - pre-sync.hook.yml
  - configMap.yml
  - deployment.yml
