apiVersion: batch/v1
kind: Job
metadata:
  generateName: vault-sync-
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
        - name: sleep
          image: busybox
          command: ['/bin/sh']
          args: ['-c', "echo 'Starting sleep'; sleep 10; echo 'Sleep finished'"]
      restartPolicy: Never
