name: CLI Pipeline

on:
  push:
    branches-ignore:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  HUSKY: 0
  RUST_TOOLCHAIN: stable
  TOOLCHAIN_PROFILE: minimal

jobs:
  build:
    name: 'Rust Build'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install stable Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: ${{ env.TOOLCHAIN_PROFILE }}
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          override: true
          components: rustfmt, clippy
      - name: Use Cache
        uses: Swatinem/rust-cache@v2
      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
      - name: Unit Tests
        uses: actions-rs/cargo@v1
        env:
          RUST_TEST_THREADS: 1
        with:
          command: test
          args: --bin propeller
      - name: Install Kubernetes Cluster
        uses: nolar/setup-k3d-k3s@v1
        with:
          version: latest
          # k3d-kube
          k3d-name: kube
          k3d-args: '-p 10250:10250 --no-rollback --k3s-arg --disable=traefik,servicelb,metrics-server@server:*'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Integration Tests
        uses: actions-rs/cargo@v1
        env:
          RUST_TEST_THREADS: 1
        with:
          command: test
          args: --test *
      - name: Extract argocd-server Logs
        if: failure()
        run: kubectl logs --selector=app.kubernetes.io/name=argocd-server --tail=-1
      - name: Print Kubernetes Cluster Status
        if: failure()
        run: kubectl get all
      - name: Build Binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --verbose
      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cli
          path: target/release/propeller
  check:
    name: 'Resources Validation'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.15.0
          cache: 'npm'
      - name: Install npm Packages
        run: npm ci
      - name: Check Format of Resources
        run: npm run prettier:format
