name: Release Pipeline

on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  HUSKY: 0
  RUST_TOOLCHAIN: stable
  TOOLCHAIN_PROFILE: minimal

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      packages: write
      pull-requests: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.15.0
          cache: 'npm'
      - name: Install npm Packages
        run: npm ci
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: ${{ env.TOOLCHAIN_PROFILE }}
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          override: true
          components: rustfmt, clippy
      - name: Use Cache
        uses: Swatinem/rust-cache@v2
      - name: Install cargo-bump
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-bump
      - name: Install cross
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cross
      - name: Semantic Release
        env:
          CROSS_REMOTE_COPY_CACHE: 1
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
